[package]
name = "hft-types"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[[bench]]
name = "latency_bench"
harness = false

[dev-dependencies]
criterion = "0.5"
